import fs from 'node:fs';
import crypto from 'node:crypto';

const packet = JSON.parse(fs.readFileSync('evaluation/fixtures/multi-source/t1/source-packet.json', 'utf8'));
const childId = process.argv[2] || 'REPLACE_WITH_REQUIREMENT_EXTRACTOR_CHILD_V1_1_ID';
const workflow = {
  name: 'PRD Genie - Multi-Source T1 Parity Canary v0.2',
  nodes: [
    { parameters:{}, id:crypto.randomUUID(), name:'Manual Trigger', type:'n8n-nodes-base.manualTrigger', typeVersion:1, position:[-520,0] },
    { parameters:{jsCode:`const packet = ${JSON.stringify(packet)};\nreturn [{json:{...packet,orchestration_context:{parent_trace_id:'TRACE-T1-MULTI-SOURCE-'+Date.now(),active_run_id:packet.run_id,environment:'connected-canary'}}}];`}, id:crypto.randomUUID(), name:'Load Canonical PB MT SN Packet', type:'n8n-nodes-base.code', typeVersion:2, position:[-280,0] },
    { parameters:{source:'database',workflowId:{__rl:true,value:childId,mode:'list',cachedResultName:'PRD Genie - Requirement Extractor Child v1.1.1'},workflowInputs:{mappingMode:'defineBelow',value:{},matchingColumns:[],schema:[],attemptToConvertTypes:false,convertFieldsToString:true},mode:'once',options:{waitForSubWorkflow:true}}, id:crypto.randomUUID(), name:'Execute Requirement Extractor Child v1.1.1', type:'n8n-nodes-base.executeWorkflow', typeVersion:1.3, position:[0,0] },
    { parameters:{jsCode:`const stage=$input.first().json; const errors=[]; const expected={'FR-001':{type:'functional_requirement',source:'SRC-T1-PB-001',quote:'The user should be able to filter reports by date range, category, and status.'},'NFR-001':{type:'non_functional_requirement',source:'SRC-T1-PB-001',quote:'Results must load in under 2 seconds.'},'STK-001':{type:'stakeholder',source:'SRC-T1-MT-001',quote:'PM: Sarah.'},'DDL-001':{type:'deadline',source:'SRC-T1-SN-001',quote:'Deadline: Q3.'}}; const items=stage.output?.items||[]; if(stage.stage!=='requirement_extraction'||stage.execution_status!=='passed'||stage.next_route!=='gap_analysis')errors.push('integration route'); if(items.length!==4||new Set(items.map(item=>item.id)).size!==4)errors.push('approved item count'); for(const [id,rule] of Object.entries(expected)){const item=items.find(candidate=>candidate.id===id);if(!item||item.type!==rule.type||!(item.evidence||[]).some(evidence=>evidence.source_id===rule.source&&evidence.quote===rule.quote))errors.push('semantic parity '+id);} if(items.some(item=>!expected[item.id]))errors.push('unsupported item'); if(stage.validation?.unsupported_claims!==0||stage.groundedness_percent!==100||stage.validation?.groundedness_percent!==100)errors.push('grounding'); if(!stage.validation?.exact_source_traceability||!stage.observability?.ingestion_accepted)errors.push('traceability or observability'); if(errors.length)throw new Error('Multi-source T1 parity canary failed: '+errors.join('; ')); return [{json:{schema_version:'1.0.0',result_type:'multi_source_t1_parity_canary_result',run_id:stage.run_id,test_id:'T1',execution_status:'completed',contract_status:'passed',current_stage:'requirement_extraction',next_route:'gap_analysis',groundedness_percent:100,unsupported_claims:0,semantic_parity:true,exact_source_traceability:true,source_packet:stage.source_packet,requirement_extraction_stage:stage,observability:{stage_trace_id:stage.observability.stage_trace_id,ingestion_accepted:stage.observability.ingestion_accepted},recorded_at:new Date().toISOString()}}];`}, id:crypto.randomUUID(), name:'Validate T1 Multi-Source Parity', type:'n8n-nodes-base.code', typeVersion:2, position:[280,0] }
  ],
  connections:{'Manual Trigger':{main:[[{node:'Load Canonical PB MT SN Packet',type:'main',index:0}]]},'Load Canonical PB MT SN Packet':{main:[[{node:'Execute Requirement Extractor Child v1.1.1',type:'main',index:0}]]},'Execute Requirement Extractor Child v1.1.1':{main:[[{node:'Validate T1 Multi-Source Parity',type:'main',index:0}]]}},
  pinData:{}, settings:{executionOrder:'v1'}, staticData:null, tags:[], triggerCount:0, updatedAt:new Date().toISOString(), versionId:crypto.randomUUID()
};
fs.writeFileSync('workflows/n8n/prd-genie-multi-source-t1-parity-orchestrator-v0.2.json', JSON.stringify(workflow,null,2)+'\n');
