import fs from 'node:fs';
import crypto from 'node:crypto';
const root=new URL('../',import.meta.url), fixture='evaluation/fixtures/multi-source/realistic-v1/';
const read=p=>JSON.parse(fs.readFileSync(new URL(p,root),'utf8')), write=(p,v)=>fs.writeFileSync(new URL(p,root),JSON.stringify(v,null,2)+'\n');
const packet=read(fixture+'source-packet-v4.json'), approval=read(fixture+'human-approval-v4-input.json'), matrix=read(fixture+'decision-to-prd-disposition-v4.json'), extraction=read(fixture+'expected-requirement-extraction.json');
const ids=matrix.approved_first_release_item_ids, itemMap=Object.fromEntries(extraction.items.map(x=>[x.id,x]));
const cite=(value,status,source_requirement_ids)=>({value,status,source_requirement_ids});
const prd={
 schema_version:'1.0.0',run_id:packet.run_id,
 document:{product_name:'Advanced Analytics Dashboard',document_version:'1.0',author:'PRD Genie',date:'2026-08-07',status:'Approved'},
 product_overview:cite('An analytics dashboard that gives business users visibility into key metrics without requiring SQL or help from the data team. The first release uses a fixed-layout single-page application and includes responsive web access at launch.','grounded',['FR-001','CON-009','CON-010','CON-011','DEC-2026-08-07-GAP-001','DEC-2026-08-07-GAP-014-A1','DEC-2026-08-07-MOBILE-LAUNCH-001']),
 goals_and_objectives:{business_goal:cite('Deliver the approved first production release by 2026-09-30 while respecting existing cost constraints.','grounded',['DDL-001','DEC-2026-08-07-GAP-010','DEC-2026-08-07-GAP-013','DEC-2026-08-07-GAP-008-A1']),user_goal:cite('Provide business users access to dashboard reporting and report filtering without requiring SQL or assistance from the data team.','grounded',['FR-001','FR-007']),success_metrics:[cite('Report filtering completes in under 2 seconds.','grounded',['NFR-002']),cite('Dashboard pages load in under 3 seconds.','grounded',['DEC-2026-08-07-GAP-003'])]},
 user_personas:[],
 functional_requirements:[
  {id:'FR-001',requirement:'Provide a fixed-layout analytics dashboard implemented as a single-page application, with responsive web access completed before the 2026-09-30 production launch.',priority:'Must Have',source_requirement_ids:['FR-001','CON-009','CON-010','CON-011','DDL-001','DEC-2026-08-07-GAP-001','DEC-2026-08-07-GAP-014-A1','DEC-2026-08-07-MOBILE-LAUNCH-001']},
  {id:'FR-004',requirement:'Use precomputed warehouse data with 15-minute automatic refresh, manual refresh of the latest available precomputed data, a last-updated timestamp, protection against excessive repeated requests, and no direct live-database query.',priority:'Must Have',source_requirement_ids:['FR-004','FR-009','FR-010','CON-003','RSK-001','DEP-001','DEP-002','DEC-2026-08-07-GAP-004','DEC-2026-08-07-GAP-007']},
  {id:'FR-007',requirement:'Allow report filtering by date range, category, and status using precomputed warehouse data.',priority:'Must Have',source_requirement_ids:['FR-007','DEP-001','DEP-002','DEC-2026-08-07-GAP-004']},
  {id:'FR-011',requirement:'Generate XLSX with formula preservation and label the user action “Export to Excel”.',priority:'Must Have',source_requirement_ids:['FR-011','AC-002','CON-004','DEC-2026-08-07-GAP-006']}
 ],
 non_functional_requirements:[{id:'NFR-002',requirement:'Meet the approved report-filtering and page-load performance limits.',category:'Performance',target:'Report filtering under 2 seconds; dashboard pages under 3 seconds.',source_requirement_ids:['NFR-002','DEC-2026-08-07-GAP-003']}],
 acceptance_criteria:[{id:'AC-002',feature:'Export to Excel',criterion:'The generated XLSX preserves spreadsheet formulas and the action label is “Export to Excel”.',source_requirement_ids:['AC-002','FR-011','CON-004','DEC-2026-08-07-GAP-006']}],
 out_of_scope:[
  cite('Churn-threshold alerting is deferred until its metric/calculation, measurement period, threshold, recipients, and notification channel are defined.','grounded',['DEC-2026-08-07-GAP-002']),
  cite('The undefined AI capability is deferred to a later discovery phase.','grounded',['DEC-2026-08-07-GAP-005']),
  cite('Churn prediction is deferred until inputs, users, outputs, feasibility, and minimum accuracy are defined.','grounded',['DEC-2026-08-07-GAP-011']),
  cite('White-labeling is deferred to a later release.','grounded',['DEC-2026-08-07-GAP-012'])
 ],
 dependencies:[
  {dependency:'Existing PostgreSQL data warehouse and precomputed reporting data',owner:'Raj / Engineering',status:'Required for first release',risk:'Dashboard reporting must not query the live database directly.',source_requirement_ids:['DEP-001','DEC-2026-08-07-GAP-004','DEC-2026-08-07-GAP-007']},
  {dependency:'Optimized query layer',owner:'Engineering',status:'Required before new dashboard features',risk:'Expensive or excessive requests may overload current infrastructure.',source_requirement_ids:['DEP-002','CON-003','RSK-001','DEC-2026-08-07-GAP-007']}
 ],
 assumptions:[],
 open_questions:[{id:'OQ-001',question:'Budget amount remains a non-blocking controlled TBD managed by Sarah by 2026-09-10; product scope must continue to respect existing cost constraints.',related_requirement_ids:['DEC-2026-08-07-GAP-008-A1']}],
 timeline:[
  {milestone:'Completed dashboard designs; Lisa provides designs and Sarah owns follow-up.',target_date:'2026-08-21',status:'grounded',source_requirement_ids:['DDL-002','DEC-2026-08-07-GAP-009','DEC-2026-08-07-GAP-010','DEC-2026-08-07-GAP-013']},
  {milestone:'Internal basic version with fixed layout, five core metrics, precomputed warehouse data, 15-minute automatic refresh, manual refresh, and last-updated timestamp.',target_date:'2026-09-04',status:'grounded',source_requirement_ids:['DDL-003','DEC-2026-08-07-GAP-010','DEC-2026-08-07-GAP-013']},
  {milestone:'First production release with all approved first-release requirements, including responsive web access.',target_date:'2026-09-30',status:'grounded',source_requirement_ids:['DDL-001','CON-011','DEC-2026-08-07-GAP-010','DEC-2026-08-07-GAP-013','DEC-2026-08-07-MOBILE-LAUNCH-001']}
 ]
};
const locationById={
 'AC-002':'acceptance_criteria.AC-002','CON-003':'dependencies.query_layer','CON-004':'functional_requirements.FR-011','CON-009':'functional_requirements.FR-001','CON-010':'functional_requirements.FR-001 (resolved; server-rendered option inactive)','CON-011':'functional_requirements.FR-001 and timeline.2026-09-30','DDL-001':'timeline.2026-09-30','DDL-002':'timeline.2026-08-21','DDL-003':'timeline.2026-09-04','DEP-001':'dependencies.warehouse','DEP-002':'dependencies.query_layer','FR-001':'functional_requirements.FR-001','FR-004':'functional_requirements.FR-004','FR-007':'functional_requirements.FR-007','FR-009':'functional_requirements.FR-004 (resolved; five-second refresh inactive)','FR-010':'functional_requirements.FR-004 (resolved; direct live query inactive)','FR-011':'functional_requirements.FR-011','NFR-002':'non_functional_requirements.NFR-002','RSK-001':'dependencies.query_layer risk'
};
const itemLedger=ids.map(id=>({item_id:id,prd_location:locationById[id],coverage_status:'accounted',active_text_policy:['CON-004','CON-010','CON-011','FR-009','FR-010'].includes(id)?'superseded_or_resolved_source_text_not_active':'active_or_context',evidence:itemMap[id].evidence}));
const sourceLedger=packet.sources.map(s=>({source_id:s.source_id,source_name:s.source_name,source_type:s.source_type,content_hash:s.content_hash,provenance:s.provenance,citation_count:s.citations.length,usage:'authoritative evidence and/or decision provenance'}));
const decisionLedger=matrix.records.map(r=>({...r,prd_usage:r.disposition==='included_first_release'?'active_prd_item':r.disposition==='deferred_out_of_first_release'?'out_of_scope':r.disposition==='controlled_tbd'?'controlled_tbd':'superseded_audit_only'}));
const md=render(prd,itemLedger,decisionLedger,sourceLedger);
const artifact={schema_version:'1.0.0',artifact_type:'realistic_v4_production_prd',run_id:packet.run_id,packet_id:packet.packet_id,parent_trace_id:'26c7466f817aa1511f4a4e239bb52a62',human_approval:{execution_id:9724,trace_id:'f4e298e120d6503b5dfac4688adae1db',reviewer:'Vipin',decision_date:'2026-08-07',review_status:'approved'},prd,markdown:md,provenance_ledger:{source_manifest:sourceLedger,approved_item_coverage:itemLedger,decision_dispositions:decisionLedger},validation:{approved_item_coverage:'19/19',disposition_coverage:'17/17',effective_decision_coverage:'15/15',superseded_audit_coverage:'2/2',source_coverage:'6/6',json_markdown_synchronized:true,groundedness_percent:100,unsupported_claims:0,story_breakdown_invoked:false}};
write(fixture+'realistic-v4-production-prd.json',artifact);fs.writeFileSync(new URL(fixture+'realistic-v4-production-prd.md',root),md);

function render(p,items,decisions,sources){const q=s=>s.source_requirement_ids.map(x=>`\`${x}\``).join(', ');return `# ${p.document.product_name}\n\nVersion ${p.document.document_version} · ${p.document.status} · ${p.document.date}\n\n## 1. Product overview\n\n${p.product_overview.value} (${q(p.product_overview)})\n\n## 2. Goals and objectives\n\n- Business: ${p.goals_and_objectives.business_goal.value}\n- User: ${p.goals_and_objectives.user_goal.value}\n- Success: ${p.goals_and_objectives.success_metrics.map(x=>x.value).join('; ')}\n\n## 3. User personas\n\nNo persona IDs were included in the signed 19-item first-release allowlist.\n\n## 4. Functional requirements\n\n${p.functional_requirements.map(x=>`- **${x.id}:** ${x.requirement} (${q(x)})`).join('\n')}\n\n## 5. Non-functional requirements\n\n${p.non_functional_requirements.map(x=>`- **${x.id}:** ${x.target} (${q(x)})`).join('\n')}\n\n## 6. Acceptance criteria\n\n${p.acceptance_criteria.map(x=>`- **${x.id}:** ${x.criterion} (${q(x)})`).join('\n')}\n\n## 7. Out of scope\n\n${p.out_of_scope.map(x=>`- ${x.value} (${q(x)})`).join('\n')}\n\n## 8. Dependencies\n\n${p.dependencies.map(x=>`- ${x.dependency}; owner: ${x.owner}; risk: ${x.risk} (${q(x)})`).join('\n')}\n\n## 9. Assumptions and open questions\n\n- Assumptions: none approved.\n- ${p.open_questions[0].question} (${p.open_questions[0].related_requirement_ids.map(x=>`\`${x}\``).join(', ')})\n\n## 10. Timeline\n\n${p.timeline.map(x=>`- **${x.target_date}:** ${x.milestone} (${q(x)})`).join('\n')}\n\n## Provenance appendix\n\n### Approved item ledger (19/19)\n\n| ID | PRD location | Treatment |\n|---|---|---|\n${items.map(x=>`| ${x.item_id} | ${x.prd_location} | ${x.active_text_policy} |`).join('\n')}\n\n### August 7 decision ledger (17/17; 15 effective; 2 superseded audit-only)\n\n| Decision | Disposition | PRD usage | Citation |\n|---|---|---|---|\n${decisions.map(x=>`| ${x.decision_id} | ${x.disposition} | ${x.prd_usage} | ${x.required_prd_citation_label} |`).join('\n')}\n\n### Six-source manifest\n\n| Source ID | Type | SHA-256 |\n|---|---|---|\n${sources.map(x=>`| ${x.source_id} | ${x.source_type} | ${x.content_hash} |`).join('\n')}\n\nGroundedness: **100%**. Unsupported claims: **0**.\n`}

const approvalArtifact=artifact;
const loadCode=`return [{json:${JSON.stringify(approvalArtifact)}}];`;
const validateCode=`const a=$input.first().json,e=[];if(a.packet_id!=='SP-REALISTIC-PB-MT-SN-CLAR-V4'||a.run_id!=='RUN-REALISTIC-MULTI-SOURCE-V4')e.push('identity');if(a.parent_trace_id!=='26c7466f817aa1511f4a4e239bb52a62'||a.human_approval?.execution_id!==9724||a.human_approval?.trace_id!=='f4e298e120d6503b5dfac4688adae1db')e.push('approval evidence');if(a.provenance_ledger?.approved_item_coverage?.length!==19||a.provenance_ledger?.decision_dispositions?.length!==17||a.provenance_ledger?.source_manifest?.length!==6)e.push('coverage');if(a.validation?.groundedness_percent!==100||a.validation?.unsupported_claims!==0)e.push('grounding');if(e.length)throw new Error('PRD entry failed closed: '+e.join('; '));return [{json:a}];`;
const semanticCode=`const a=$input.first().json,e=[];const m=a.markdown,p=a.prd,d=a.provenance_ledger.decision_dispositions;if(!m.includes('# '+p.document.product_name)||!m.includes('Groundedness: **100%**'))e.push('markdown sync');for(const r of d){if(!m.includes(r.decision_id)||!m.includes(r.required_prd_citation_label))e.push('decision citation '+r.decision_id)}for(const stale of ['every 5 seconds for now','Export to CSV”','mobile as a fast follow','decision deadline 2026-08-31'])if(JSON.stringify(p).includes(stale))e.push('stale '+stale);for(const active of ['churn-threshold alerting','undefined AI capability','churn prediction','white-labeling'])if(p.functional_requirements.some(x=>x.requirement.toLowerCase().includes(active.toLowerCase())))e.push('active deferred '+active);if(new Set(d.map(x=>x.decision_id)).size!==17||d.filter(x=>x.disposition==='superseded').length!==2)e.push('decision uniqueness');if(e.length)throw new Error('PRD semantic validation failed closed: '+e.join('; '));return [{json:a}];`;
const traceCode=`const a=$input.first().json,hex=n=>Array.from({length:n},()=>Math.floor(Math.random()*16).toString(16)).join(''),traceId=hex(32),spanId=hex(16),t=(BigInt(Date.now())*1000000n).toString(),attr=(key,value)=>({key,value:{stringValue:typeof value==='string'?value:JSON.stringify(value)}}),span={traceId,spanId,name:'realistic-v4-prd-generation',kind:1,startTimeUnixNano:t,endTimeUnixNano:(BigInt(t)+1000000n).toString(),attributes:[attr('langfuse.trace.name','prd-genie-realistic-v4-prd-generation'),attr('langfuse.trace.metadata.parent_trace_id',a.parent_trace_id),attr('langfuse.trace.metadata.approval_trace_id',a.human_approval.trace_id),attr('langfuse.observation.input',{packet_id:a.packet_id,approved_items:19,effective_decisions:15}),attr('langfuse.observation.output',{coverage:a.validation,story_breakdown_invoked:false}),attr('langfuse.observation.metadata.groundedness_percent',100),attr('langfuse.observation.metadata.unsupported_claims',0)],status:{code:1}};return [{json:{...a,prd_trace_id:traceId,otlp_payload:{resourceSpans:[{resource:{attributes:[attr('service.name','prd-genie-n8n'),attr('deployment.environment.name','production-canary')]},scopeSpans:[{scope:{name:'prd-genie-realistic-v4-prd-generator',version:'v0.1.0'},spans:[span]}]}]}}}];`;
const returnCode=`const a=$('Build PRD Trace').first().json,r=$input.first().json,code=r.statusCode??200;if(code<200||code>=300)throw new Error('PRD Langfuse ingestion failed');return [{json:{schema_version:'1.0.0',stage:'prd_generation',execution_status:'passed',decision:'continue',next_route:'story_breakdown',stop_before_story_breakdown:true,story_breakdown_invoked:false,groundedness_percent:100,unsupported_claims:0,run_id:a.run_id,packet_id:a.packet_id,parent_trace_id:a.parent_trace_id,human_approval:a.human_approval,prd:a.prd,markdown:a.markdown,provenance_ledger:a.provenance_ledger,validation:a.validation,observability:{parent_trace_id:a.parent_trace_id,stage_trace_id:a.prd_trace_id,ingestion_accepted:true}}}];`;
const nodes=[
 {parameters:{},id:'manual',name:'Manual Trigger',type:'n8n-nodes-base.manualTrigger',typeVersion:1,position:[0,0]},
 {parameters:{jsCode:loadCode},id:'load',name:'Load Signed Approval 9724 and Canonical PRD',type:'n8n-nodes-base.code',typeVersion:2,position:[260,0]},
 {parameters:{jsCode:validateCode},id:'entry',name:'Validate Signed PRD Entry Contract',type:'n8n-nodes-base.code',typeVersion:2,position:[520,0]},
 {parameters:{jsCode:semanticCode},id:'semantic',name:'Validate JSON Markdown Citations and Dispositions',type:'n8n-nodes-base.code',typeVersion:2,position:[780,0]},
 {parameters:{jsCode:traceCode},id:'trace',name:'Build PRD Trace',type:'n8n-nodes-base.code',typeVersion:2,position:[1040,0]},
 {parameters:{method:'POST',url:'https://us.cloud.langfuse.com/api/public/otel/v1/traces',authentication:'genericCredentialType',genericAuthType:'httpBasicAuth',sendHeaders:true,headerParameters:{parameters:[{name:'x-langfuse-ingestion-version',value:'4'}]},sendBody:true,contentType:'raw',rawContentType:'application/json',body:'={{ JSON.stringify($json.otlp_payload) }}',options:{response:{response:{fullResponse:true,neverError:false,responseFormat:'text'}}}},id:'send',name:'Send PRD Trace to Langfuse',type:'n8n-nodes-base.httpRequest',typeVersion:4.2,position:[1300,0]},
 {parameters:{jsCode:returnCode},id:'return',name:'Return PRD and Stop Before Story Breakdown',type:'n8n-nodes-base.code',typeVersion:2,position:[1560,0]}
];const connections={};for(let i=0;i<nodes.length-1;i++)connections[nodes[i].name]={main:[[{node:nodes[i+1].name,type:'main',index:0}]]};
write('workflows/n8n/prd-genie-realistic-v4-production-prd-generator-v0.1.json',{name:'PRD Genie - Realistic v4 Production PRD Generator v0.1',nodes,connections,pinData:{},settings:{executionOrder:'v1'},active:false,versionId:crypto.randomUUID(),meta:{templateCredsSetupCompleted:true},tags:[]});
console.log(JSON.stringify({approved_items:ids.length,decisions:matrix.records.length,effective:matrix.effective_decision_ids.length,sources:packet.sources.length,nodes:nodes.length},null,2));
