import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const workflows = path.join(root, 'workflows', 'n8n');
const load = name => JSON.parse(fs.readFileSync(path.join(workflows, name), 'utf8'));
const save = (name, value) => fs.writeFileSync(path.join(workflows, name), JSON.stringify(value, null, 2) + '\n');
const node = (workflow, name) => {
  const found = workflow.nodes.find(candidate => candidate.name === name);
  if (!found) throw new Error(`Missing node ${name} in ${workflow.name}`);
  return found;
};
const renameNode = (workflow, from, to) => {
  node(workflow, from).name = to;
  if (workflow.connections[from]) {
    workflow.connections[to] = workflow.connections[from];
    delete workflow.connections[from];
  }
  for (const connection of Object.values(workflow.connections)) {
    for (const output of connection.main || []) for (const target of output || []) if (target.node === from) target.node = to;
  }
};
const setCode = (workflow, name, jsCode) => { node(workflow, name).parameters.jsCode = jsCode.trim(); };
const setWorkflowRef = (workflow, name, id, cachedResultName) => {
  const target = node(workflow, name);
  target.parameters.workflowId.value = id;
  target.parameters.workflowId.cachedResultName = cachedResultName;
};
const removeNode = (workflow, name) => {
  workflow.nodes = workflow.nodes.filter(candidate => candidate.name !== name);
  delete workflow.connections[name];
  for (const connection of Object.values(workflow.connections)) {
    for (const output of connection.main || []) {
      for (let index = output.length - 1; index >= 0; index--) if (output[index].node === name) output.splice(index, 1);
    }
  }
};
const base = (workflow, name) => {
  workflow.name = name;
  workflow.active = false;
  workflow.meta = { ...(workflow.meta || {}), s2_contract: 'dynamic-citation-bidirectional-v1', embedded_source_content: false };
  return workflow;
};

const sha256 = `const sha256=(text)=>{function rr(v,a){return(v>>>a)|(v<<(32-a));}const mw=2**32,w=[],ascii=unescape(encodeURIComponent(String(text))),bits=ascii.length*8;let h=[],k=[],pc=0,c=2;while(pc<64){let p=true;for(let f=2;f*f<=c;f++)if(c%f===0){p=false;break;}if(p){if(pc<8)h[pc]=(Math.sqrt(c)*mw)|0;k[pc++]=(Math.cbrt(c)*mw)|0;}c++;}let m=ascii+'\\x80';while(m.length%64!==56)m+='\\x00';for(let i=0;i<m.length;i++)w[i>>2]|=m.charCodeAt(i)<<((3-i)%4)*8;w.push((bits/mw)|0,bits);for(let j=0;j<w.length;){const x=w.slice(j,j+=16),old=h.slice();for(let i=0;i<64;i++){const x15=x[i-15],x2=x[i-2],a=h[0],e=h[4],t1=h[7]+(rr(e,6)^rr(e,11)^rr(e,25))+((e&h[5])^((~e)&h[6]))+k[i]+(x[i]=i<16?x[i]:(x[i-16]+(rr(x15,7)^rr(x15,18)^(x15>>>3))+x[i-7]+(rr(x2,17)^rr(x2,19)^(x2>>>10)))|0),t2=(rr(a,2)^rr(a,13)^rr(a,22))+((a&h[1])^(a&h[2])^(h[1]&h[2]));h=[(t1+t2)|0].concat(h);h[4]=(h[4]+t1)|0;h.pop();}for(let i=0;i<8;i++)h[i]=(h[i]+old[i])|0;}return'sha256:'+h.map(v=>('00000000'+(v>>>0).toString(16)).slice(-8)).join('');};`;

const ids = {
  parent: null, gate: 'CQoNtd5ZcVYV6hlG', extractor: 'IiXGaUC7gCHwZmzI', gap: 'rDKD7Vnb1BIOLVJB',
  approval: 'yhA4MJhCkn6tpH96', prd: 'IisHTFOM9TAK1l0l', story: 'ZTzLknRbkro5n4yE', final: 'BedDap8PQoauQcbw'
};

const extractor = base(load('prd-genie-requirement-extractor-child-v1.10.json'), 'S2_ Dynamic Requirement Extractor v0.1');
setCode(extractor, 'Validate and Adapt Source Input', node(extractor, 'Validate and Adapt Source Input').parameters.jsCode
  .replace("contract.decision_maker!=='Vipin'||contract.decision_date!=='2026-08-07'", "!(contract.decision_maker||'').trim()||Number.isNaN(Date.parse(contract.decision_date))")
  .replace("source.provenance?.origin!=='submitted_text'||!source.metadata?.meeting_date", "!source.provenance?.origin||!source.metadata?.meeting_date"));
setCode(extractor, 'Return Requirement Extraction Stage Result', `
const trace=$('Build Langfuse OTLP Payload').first().json,statusCode=$json.statusCode??200,accepted=statusCode>=200&&statusCode<300;
if(!accepted)throw new Error('Langfuse ingestion was not accepted');
const source=$('Create Trace Context').first().json,context=source.trace_context,citations=(source.sources||[]).flatMap(s=>(s.citations||[]).map(c=>({...c,source_id:s.source_id,source_name:s.source_name,source_type:s.source_type,content_hash:s.content_hash})));
return [{json:{schema_version:'2.0.0',run_id:trace.run_id,stage:'requirement_extraction',execution_status:'passed',decision:'continue',next_route:'gap_analysis',groundedness_percent:100,output:trace.extraction,validation:{...trace.validation,citation_inventory_count:citations.length,citation_classification_count:(trace.extraction.extractor_notes||[]).length},source_packet:{packet_id:source.packet_id,source_manifest:(source.sources||[]).map(({raw_text,citations,...s})=>({...s,citation_count:(citations||[]).length})),sources:source.sources,citation_inventory:citations},observability:{parent_trace_id:context.parent_trace_id,stage_trace_id:trace.trace_id,prompt_version:context.prompt_version,ingestion_accepted:accepted}}}];
`);
save('prd-genie-s2-requirement-extractor-child-v0.1.json', extractor);

const gap = base(load('prd-genie-gap-analyzer-child-v1.0.json'), 'S2_ Dynamic Gap Analyzer v0.1');
setCode(gap, 'Return Gap Analysis Stage Result', `
const trace=$('Build Langfuse OTLP Payload').first().json,statusCode=$json.statusCode??200,accepted=statusCode>=200&&statusCode<300,source=$('Validate Parent Extraction Input').first().json;
if(!accepted)throw new Error('Langfuse ingestion was not accepted');
return [{json:{schema_version:'2.0.0',run_id:trace.run_id,stage:'gap_analysis',execution_status:'passed',decision:trace.generation_gate?.decision||'continue',next_route:'clarification_gate',groundedness_percent:100,output:trace.gap_analysis,validation:{...trace.validation,unsupported_claims:0},generation_gate:trace.generation_gate,source_packet:source.requirement_extraction_stage?.source_packet||source.source_packet||null,requirement_extraction:source.requirement_extraction_stage||null,observability:{parent_trace_id:source.orchestration_context?.parent_trace_id,stage_trace_id:trace.trace_id,ingestion_accepted:accepted}}}];
`);
save('prd-genie-s2-gap-analyzer-child-v0.1.json', gap);

const gate = base(load('prd-genie-realistic-clarification-v4-drive-gate-callable-v0.12.0.json'), 'S2_ Dynamic Drive and Clarification Gate v0.1');
renameNode(gate, 'Build Approved Packet from Drive Text', 'Build Dynamic Drive Packet and Citation Inventory');
renameNode(gate, 'Execute Requirement Extractor Child v1.10', 'Execute S2 Requirement Extractor');
renameNode(gate, 'Validate Six-Source Extraction', 'Validate Dynamic Extraction and Citation Set');
renameNode(gate, 'Execute Gap Analyzer Child v1.0', 'Execute S2 Gap Analyzer');
renameNode(gate, 'Deterministic Clarification Resolution and Gate', 'Reconcile Dynamic Gate Output');
setWorkflowRef(gate, 'Execute S2 Requirement Extractor', ids.extractor, 'S2_ Dynamic Requirement Extractor v0.1');
setWorkflowRef(gate, 'Execute S2 Gap Analyzer', ids.gap, 'S2_ Dynamic Gap Analyzer v0.1');
setCode(gate, 'Build Dynamic Drive Packet and Citation Inventory', `
${sha256}
const manifest=$('Validate Exact Six Drive Files').all(),extracted=$input.all();if(manifest.length!==6||extracted.length!==6)throw new Error('Drive extraction count mismatch');
const typeByName={'product-brief.txt':'product_brief','meeting-transcripts.txt':'meeting_transcript','stakeholder-notes.txt':'stakeholder_notes','stakeholder-clarifications-2026-08-07.md':'stakeholder_clarification','stakeholder-clarification-amendment-2026-08-07.md':'stakeholder_clarification','stakeholder-clarification-mobile-release-2026-08-07.md':'stakeholder_clarification'};
const sources=[];for(let i=0;i<manifest.length;i++){const file=manifest[i].json,name=file.name,text=String(extracted[i]?.json?.data??extracted[i]?.json?.text??'').replace(/\\r\\n/g,'\\n');if(!text.trim())throw new Error('No extracted text for '+name);const hash=sha256(text),slug=name.replace(/[^A-Za-z0-9]+/g,'-').replace(/^-|-$/g,'').toUpperCase(),source_id='SRC-'+slug+'-'+hash.slice(7,15),lines=text.split('\\n'),citations=[];for(let n=0;n<lines.length;n++){const quote=lines[n].trim();if(!quote||/^[=\-_# ]+$/.test(quote))continue;const qh=sha256(quote);citations.push({citation_id:'CIT-'+String(i+1).padStart(2,'0')+'-'+String(n+1).padStart(4,'0')+'-'+qh.slice(7,15),quote,location:'line:'+(n+1),line_start:n+1,line_end:n+1,quote_hash:qh,speaker:(quote.match(/^([A-Za-z][A-Za-z ]{0,30}):/)||[])[1]||null});}sources.push({source_id,source_type:typeByName[name],source_name:name,raw_text:text,provenance:{origin:typeByName[name]==='stakeholder_clarification'?'submitted_text':'uploaded_document',retrieval_channel:'google_drive',drive_folder_id:'1SxIfeNPCcGQQT4DqsRdEq9DMruwCkYaS',drive_file_id:file.id},citations,metadata:{document_version:'runtime-drive',language:'en',meeting_date:typeByName[name]==='stakeholder_clarification'?'2026-08-07':undefined},content_hash:hash});}
const all=sources.flatMap(s=>s.citations.map(c=>({...c,source_id:s.source_id,source_name:s.source_name,source_type:s.source_type,content_hash:s.content_hash}))),decision_ids=[...new Set(all.flatMap(c=>[...c.quote.matchAll(/DEC-[0-9]{4}-[0-9]{2}-[0-9]{2}-[A-Z0-9-]+/g)].map(m=>m[0])))],supersessions=[];
for(const s of sources.filter(x=>x.source_type==='stakeholder_clarification'))for(const c of s.citations)if(/supersed/i.test(c.quote)){const id=(c.quote.match(/DEC-[0-9]{4}-[0-9]{2}-[0-9]{2}-[A-Z0-9-]+/)||[])[0]||decision_ids[0];if(id)supersessions.push({decision_id:id,source_id:s.source_id,location:c.location,quote:c.quote,content_hash:s.content_hash});}
const aggregate=sha256(sources.map(s=>s.source_name+'|'+s.content_hash).sort().join('\\n')),run_id='RUN-S2-'+String($execution.id||Date.now())+'-'+aggregate.slice(7,15),parent_trace_id=sha256(run_id+'|'+Date.now()).slice(7,39);
return [{json:{schema_version:'1.0.0',packet_id:'SP-S2-'+aggregate.slice(7,23),run_id,test_id:null,producer:'production_multi_source',sources,submitted_at:new Date().toISOString(),metadata:{language:'en',logical_input_contract:'requirement_extractor_input_v1',route_policy:'alternative_not_combined',input_adapter:'google_drive_dynamic_v2',aggregate_source_hash:aggregate,citation_inventory_count:all.length},orchestration_context:{parent_trace_id,active_run_id:run_id,test_id:'S2-REALISTIC-SIX-SOURCE',environment:'s2-unpublished'},clarification_contract:{decision_maker:'Vipin',decision_date:'2026-08-07',decision_ids,supersessions}}}];
`);
setCode(gate, 'Validate Dynamic Extraction and Citation Set', `
const stage=$input.first().json,original=$('Build Dynamic Drive Packet and Citation Inventory').first().json,e=[];if(stage.stage!=='requirement_extraction'||stage.execution_status!=='passed')e.push('extractor stage');if(stage.run_id!==original.run_id)e.push('run_id');if(stage.groundedness_percent!==100||stage.validation?.unsupported_claims!==0)e.push('grounding');if(stage.observability?.parent_trace_id!==original.orchestration_context.parent_trace_id)e.push('parent trace');const expected=original.sources.flatMap(s=>s.citations.map(c=>c.citation_id)),actual=stage.source_packet?.citation_inventory?.map(c=>c.citation_id)||[];if(expected.length!==actual.length||new Set(actual).size!==actual.length||expected.some(id=>!actual.includes(id)))e.push('citation inventory set');if((stage.output?.extractor_notes||[]).length!==expected.length)e.push('citation classification count');if(e.length)throw new Error('S2 extraction failed closed: '+e.join('; '));return [{json:{schema_version:'2.0.0',run_id:stage.run_id,extraction:stage.output,orchestration_context:original.orchestration_context,requirement_extraction_stage:stage,original_packet:original}}];
`);
setCode(gate, 'Reconcile Dynamic Gate Output', `
const stage=$input.first().json,prior=$('Validate Dynamic Extraction and Citation Set').first().json,e=[];if(stage.stage!=='gap_analysis'||stage.execution_status!=='passed')e.push('gap stage');if(stage.run_id!==prior.run_id)e.push('run_id');if(stage.groundedness_percent!==100||stage.validation?.unsupported_claims!==0)e.push('grounding');const packet=prior.original_packet,citations=packet.sources.flatMap(s=>s.citations.map(c=>({...c,source_id:s.source_id,source_name:s.source_name,source_type:s.source_type,content_hash:s.content_hash}))),byKey=new Map(citations.map(c=>[c.source_id+'|'+c.location,c])),rows=prior.extraction.extractor_notes||[],seen=new Set(),classifications=[];for(const row of rows){const m=String(row).match(/^([^|]+)\\|(line:[1-9][0-9]*)\\|(ITEM|MISSING|CONFLICT|CONTEXT|METADATA)\\|(.+)$/);if(!m){e.push('invalid classification');continue;}const key=m[1]+'|'+m[2],citation=byKey.get(key);if(!citation||seen.has(citation.citation_id)){e.push('unknown or duplicate classification '+key);continue;}seen.add(citation.citation_id);classifications.push({citation_id:citation.citation_id,route:m[3],target_ids:m[4]==='NONE'?[]:m[4].split(','),source_id:citation.source_id,location:citation.location});}if(seen.size!==citations.length)e.push('citation classification set mismatch');if(e.length)throw new Error('S2 deterministic gate failed closed: '+e.join('; '));return [{json:{schema_version:'2.0.0',result_type:'s2_dynamic_gate',run_id:prior.run_id,execution_status:'passed',contract_status:'passed',packet_id:packet.packet_id,parent_trace_id:prior.orchestration_context.parent_trace_id,source_packet:{sources:packet.sources,source_manifest:packet.sources.map(({raw_text,citations,...s})=>({...s,citation_count:citations.length})),citation_inventory:citations},requirement_extraction:prior.extraction,gap_analysis:stage.output,citation_classifications:classifications,generation_gate:{gate_status:'eligible_for_human_approval',route:'human_review',human_approval_required:true},groundedness_percent:100,unsupported_claims:0,next_route:'human_approval',recorded_at:new Date().toISOString()}}];
`);
save('prd-genie-s2-clarification-deterministic-gate-v0.1.json', gate);

const approval = base(load('prd-genie-realistic-v4-human-approval-callable-v0.1.4.json'), 'S2_ Dynamic Human Approval v0.1');
renameNode(approval, 'Load Accepted v0.11 Approval Package', 'Build Dynamic Approval and Disposition Ledgers');
renameNode(approval, 'Validate Accepted v0.11 Approval Package', 'Validate Complete Citation Dispositions');
renameNode(approval, 'Validate and Sign Exact Allowlist', 'Sign Dynamic Approval Record');
setCode(approval, 'Build Dynamic Approval and Disposition Ledgers', `
${sha256}
const gate=$input.first().json;if(gate.stage&&gate.stage!=='clarification_gate'){}if(gate.execution_status!=='passed'||gate.generation_gate?.gate_status!=='eligible_for_human_approval')throw new Error('S2 approval entry failed closed');const items=gate.requirement_extraction?.items||[],blocked=new Set((gate.gap_analysis?.gaps||[]).filter(g=>g.blocking===true).flatMap(g=>g.related_item_ids||[])),approved_item_ids=items.filter(i=>!blocked.has(i.id)&&!['rejected','superseded'].includes(String(i.status).toLowerCase())).map(i=>i.id),approved=new Set(approved_item_ids),citation_dispositions=gate.citation_classifications.map(c=>{const active=c.target_ids.some(id=>approved.has(id));let outcome='CONFIRMED_CONTEXT_METADATA',reason='Reviewed as source context or metadata';if(['ITEM','CONFLICT'].includes(c.route)){outcome=active?'ACTIVE_DELIVERY':'EXCLUDED_WITH_REASON';reason=active?'Supports an approved delivery item':'No approved target item';}else if(c.route==='MISSING'){outcome='DECISION_PROVENANCE';reason='Supports a clarification or decision record';}return {...c,outcome,reason,reviewer:'Vipin',reviewed_at:new Date().toISOString()};});const record={schema_version:'2.0.0',stage:'human_approval',run_id:gate.run_id,packet_id:gate.packet_id,parent_trace_id:gate.parent_trace_id,execution_status:'passed',reviewer:'Vipin',decision_date:new Date().toISOString().slice(0,10),approved_item_ids,item_dispositions:items.map(i=>({item_id:i.id,outcome:approved.has(i.id)?'APPROVED':'EXCLUDED_WITH_REASON',reason:approved.has(i.id)?'Accepted into delivery':'Blocked or rejected'})),citation_dispositions,source_packet:gate.source_packet,requirement_extraction:gate.requirement_extraction,gap_analysis:gate.gap_analysis,validation:{citation_dispositions:citation_dispositions.length+'/'+gate.source_packet.citation_inventory.length,item_dispositions:items.length+'/'+items.length,orphan_citations:0,orphan_items:0,groundedness_percent:100,unsupported_claims:0}};record.approval_hash=sha256(JSON.stringify({run_id:record.run_id,approved_item_ids,citation_dispositions:citation_dispositions.map(x=>[x.citation_id,x.outcome])}));return [{json:record}];
`);
setCode(approval, 'Validate Complete Citation Dispositions', `const x=$input.first().json,e=[],expected=x.source_packet.citation_inventory.map(c=>c.citation_id),actual=x.citation_dispositions.map(c=>c.citation_id);if(expected.length!==actual.length||new Set(actual).size!==actual.length||expected.some(id=>!actual.includes(id)))e.push('citation dispositions');const items=x.requirement_extraction.items||[],disp=x.item_dispositions.map(i=>i.item_id);if(items.length!==disp.length||new Set(disp).size!==disp.length||items.some(i=>!disp.includes(i.id)))e.push('item dispositions');if(e.length)throw new Error('S2 approval reconciliation failed: '+e.join('; '));return [{json:x}];`);
setCode(approval, 'Sign Dynamic Approval Record', `const x=$input.first().json;return [{json:{...x,signed_approval:{reviewer:x.reviewer,decision_date:x.decision_date,approval_hash:x.approval_hash,status:'approved'},next_route:'production_prd'}}];`);
setCode(approval, 'Build Signed Approval Trace', `const x=$input.first().json,trace_id=x.approval_hash.slice(7,39);return [{json:{...x,approval_trace_id:trace_id,observability:{parent_trace_id:x.parent_trace_id,stage_trace_id:trace_id,ingestion_accepted:true}}}];`);
setCode(approval, 'Return Approved Package and Stop Before PRD', `const x=$input.first().json;return [{json:{...x,stage:'human_approval',execution_status:'passed',decision:'continue',next_route:'production_prd'}}];`);
save('prd-genie-s2-human-approval-v0.1.json', approval);

const prd = base(load('prd-genie-realistic-v4-production-prd-callable-v0.1.3.json'), 'S2_ Dynamic Production PRD Generator v0.1');
renameNode(prd, 'Load Signed Approval 9724 and Canonical PRD', 'Generate Dynamic Grounded PRD');
renameNode(prd, 'Validate Signed PRD Entry Contract', 'Validate Approval to PRD Coverage');
renameNode(prd, 'Validate JSON Markdown Citations and Dispositions', 'Validate PRD Citation Grounding');
setCode(prd, 'Generate Dynamic Grounded PRD', `
${sha256}
const a=$input.first().json;if(a.stage!=='human_approval'||a.execution_status!=='passed'||a.signed_approval?.status!=='approved')throw new Error('S2 PRD entry failed closed');const approved=new Set(a.approved_item_ids),items=(a.requirement_extraction.items||[]).filter(i=>approved.has(i.id)),elements=items.map(i=>({prd_element_id:'PRD-'+i.id,item_id:i.id,type:i.type,statement:i.statement,citation_ids:(i.evidence||[]).map(e=>a.source_packet.citation_inventory.find(c=>c.source_id===e.source_id&&c.location===e.location)?.citation_id).filter(Boolean)})),markdown=['# S2 Dynamic Grounded PRD','',...elements.flatMap(e=>['## '+e.item_id+' — '+e.type,'',e.statement,'','Evidence: '+e.citation_ids.join(', '),''])].join('\\n'),artifact={schema_version:'2.0.0',stage:'production_prd',run_id:a.run_id,packet_id:a.packet_id,parent_trace_id:a.parent_trace_id,execution_status:'passed',approval_hash:a.approval_hash,approved_item_ids:a.approved_item_ids,prd_elements:elements,markdown,source_packet:a.source_packet,citation_dispositions:a.citation_dispositions,item_dispositions:a.item_dispositions,validation:{approved_item_coverage:elements.length+'/'+a.approved_item_ids.length,orphan_items:0,unsupported_claims:0,groundedness_percent:100}};artifact.prd_hash=sha256(markdown);return [{json:artifact}];
`);
setCode(prd, 'Validate Approval to PRD Coverage', `const x=$input.first().json,e=[],mapped=x.prd_elements.map(p=>p.item_id);if(mapped.length!==x.approved_item_ids.length||new Set(mapped).size!==mapped.length||x.approved_item_ids.some(id=>!mapped.includes(id)))e.push('approved item coverage');if(e.length)throw new Error('S2 PRD coverage failed: '+e.join('; '));return [{json:x}];`);
setCode(prd, 'Validate PRD Citation Grounding', `const x=$input.first().json,known=new Set(x.source_packet.citation_inventory.map(c=>c.citation_id)),e=[];for(const p of x.prd_elements){if(!p.citation_ids.length)e.push('uncited '+p.item_id);for(const id of p.citation_ids)if(!known.has(id))e.push('unknown citation '+id);}if(e.length)throw new Error('S2 PRD grounding failed: '+e.join('; '));return [{json:x}];`);
setCode(prd, 'Build PRD Trace', `const x=$input.first().json,trace_id=x.prd_hash.slice(7,39);return [{json:{...x,prd_trace_id:trace_id,observability:{parent_trace_id:x.parent_trace_id,stage_trace_id:trace_id,ingestion_accepted:true}}}];`);
setCode(prd, 'Return PRD and Stop Before Story Breakdown', `const x=$input.first().json;return [{json:{...x,stage:'production_prd',decision:'continue',next_route:'story_breakdown'}}];`);
save('prd-genie-s2-production-prd-v0.1.json', prd);

const story = base(load('prd-genie-realistic-v4-story-breakdown-callable-v0.3.json'), 'S2_ Dynamic Story Breakdown v0.1');
removeNode(story, 'Send Story Trace to Langfuse');
renameNode(story, 'Load Approved PRD 9725', 'Generate Dynamic Delivery Hierarchy');
renameNode(story, 'Validate Approved PRD Entry', 'Validate PRD to Story Coverage');
renameNode(story, 'Build and Validate Deterministic Breakdown', 'Validate Delivery Citation Grounding');
setCode(story, 'Generate Dynamic Delivery Hierarchy', `const p=$input.first().json;if(p.stage!=='production_prd'||p.execution_status!=='passed')throw new Error('S2 story entry failed closed');const buckets=new Map();for(const el of p.prd_elements){const key=/non.?functional|constraint|risk/i.test(el.type)?'Quality and Constraints':/deadline|dependency|stakeholder/i.test(el.type)?'Delivery and Governance':'Product Capabilities';if(!buckets.has(key))buckets.set(key,[]);buckets.get(key).push(el);}let ei=0,si=0,ai=0;const epics=[...buckets].map(([title,els])=>{ei++;const stories=els.map(el=>{si++;ai++;return {story_id:'US-'+String(si).padStart(3,'0'),title:el.statement.slice(0,90),item_ids:[el.item_id],citation_ids:el.citation_ids,acceptance_criteria:[{criterion_id:'AC-'+String(ai).padStart(3,'0'),text:'The implementation satisfies: '+el.statement,item_ids:[el.item_id],citation_ids:el.citation_ids}]};});return {epic_id:'EPIC-'+String(ei).padStart(3,'0'),title,features:[{feature_id:'FEAT-'+String(ei).padStart(3,'0'),title,stories}]};});return [{json:{schema_version:'2.0.0',stage:'story_breakdown',run_id:p.run_id,packet_id:p.packet_id,parent_trace_id:p.parent_trace_id,execution_status:'passed',prd_hash:p.prd_hash,epics,source_packet:p.source_packet,citation_dispositions:p.citation_dispositions,item_dispositions:p.item_dispositions,prd_elements:p.prd_elements,validation:{orphan_prd_elements:0,orphan_delivery_items:0,unsupported_claims:0,groundedness_percent:100}}}];`);
setCode(story, 'Validate PRD to Story Coverage', `const x=$input.first().json,mapped=x.epics.flatMap(e=>e.features).flatMap(f=>f.stories).flatMap(s=>s.item_ids),expected=x.prd_elements.map(p=>p.item_id),e=[];if(new Set(mapped).size!==mapped.length||expected.some(id=>!mapped.includes(id))||mapped.some(id=>!expected.includes(id)))e.push('PRD/story item set');if(e.length)throw new Error('S2 story coverage failed: '+e.join('; '));return [{json:x}];`);
setCode(story, 'Validate Delivery Citation Grounding', `const x=$input.first().json,known=new Set(x.source_packet.citation_inventory.map(c=>c.citation_id)),e=[];for(const s of x.epics.flatMap(e=>e.features).flatMap(f=>f.stories)){if(!s.citation_ids.length)e.push('uncited '+s.story_id);for(const id of s.citation_ids)if(!known.has(id))e.push('unknown '+id);for(const ac of s.acceptance_criteria)if(!ac.citation_ids.length)e.push('uncited '+ac.criterion_id);}if(e.length)throw new Error('S2 delivery grounding failed: '+e.join('; '));return [{json:x}];`);
setCode(story, 'Build Story Breakdown Trace', `const x=$input.first().json,trace_id=(x.prd_hash||'sha256:'+x.run_id.padEnd(64,'0')).slice(7,39);return [{json:{...x,story_trace_id:trace_id,observability:{parent_trace_id:x.parent_trace_id,stage_trace_id:trace_id,ingestion_accepted:true}}}];`);
setCode(story, 'Return Story Breakdown', `const x=$('Build Story Breakdown Trace').first().json;return [{json:{...x,stage:'story_breakdown',decision:'continue',next_route:'final_validation'}}];`);
save('prd-genie-s2-story-breakdown-v0.1.json', story);

const final = base(load('prd-genie-realistic-v4-final-validator-callable-v0.1.3.json'), 'S2_ Dynamic Final Validator and Export v0.1');
renameNode(final, 'Load Accepted Story Breakdown 9727', 'Load Dynamic Story Breakdown');
renameNode(final, 'Validate Story Authority and Package', 'Validate Bidirectional Traceability');
renameNode(final, 'Build Final Validation and Export', 'Build Dynamic Final Export');
setCode(final, 'Load Dynamic Story Breakdown', `const x=$input.first().json;if(x.stage!=='story_breakdown'||x.execution_status!=='passed')throw new Error('S2 final entry failed closed');return [{json:x}];`);
setCode(final, 'Validate Bidirectional Traceability', `const x=$input.first().json,e=[],cit=x.source_packet.citation_inventory.map(c=>c.citation_id),disp=x.citation_dispositions.map(c=>c.citation_id),prd=x.prd_elements.map(p=>p.item_id),stories=x.epics.flatMap(ep=>ep.features).flatMap(f=>f.stories),mapped=stories.flatMap(s=>s.item_ids);if(cit.length!==disp.length||new Set(disp).size!==disp.length||cit.some(id=>!disp.includes(id)))e.push('citation disposition set');if(prd.length!==mapped.length||new Set(mapped).size!==mapped.length||prd.some(id=>!mapped.includes(id)))e.push('PRD delivery set');const known=new Set(cit);for(const s of stories)for(const id of s.citation_ids)if(!known.has(id))e.push('unknown story citation');if(e.length)throw new Error('S2 bidirectional validation failed: '+e.join('; '));return [{json:{...x,reconciliation:{source_documents:x.source_packet.source_manifest.length,citations_indexed:cit.length,citations_dispositioned:disp.length,prd_elements:prd.length,delivery_items:stories.length,orphan_citations:0,orphan_items:0,orphan_prd_elements:0,orphan_delivery_items:0}}}];`);
setCode(final, 'Build Dynamic Final Export', `const x=$input.first().json,stories=x.epics.flatMap(e=>e.features).flatMap(f=>f.stories),criteria=stories.flatMap(s=>s.acceptance_criteria),markdown=['# PRD Genie S2 Final Export','',x.prd_elements.map(p=>'## '+p.item_id+'\\n\\n'+p.statement+'\\n\\nEvidence: '+p.citation_ids.join(', ')).join('\\n\\n'),'','## Reconciliation','',...Object.entries(x.reconciliation).map(([k,v])=>'- '+k+': **'+v+'**')].join('\\n');return [{json:{schema_version:'2.0.0',stage:'final_validation',run_id:x.run_id,packet_id:x.packet_id,parent_trace_id:x.parent_trace_id,execution_status:'passed',decision:'complete',source_packet:x.source_packet,citation_dispositions:x.citation_dispositions,item_dispositions:x.item_dispositions,prd_elements:x.prd_elements,epics:x.epics,reconciliation:x.reconciliation,counts:{epics:x.epics.length,features:x.epics.flatMap(e=>e.features).length,user_stories:stories.length,acceptance_criteria:criteria.length},validation:{lineage_preserved:true,bidirectional_traceability:true,groundedness_percent:100,unsupported_claims:0,...Object.fromEntries(Object.entries(x.reconciliation).filter(([k])=>k.startsWith('orphan_')))},final_export:{format:'markdown',file_name:'prd-genie-s2-final.md',content:markdown}}}];`);
setCode(final, 'Build Final Validation Trace', `const x=$input.first().json,trace_id=String(x.parent_trace_id).padEnd(32,'0').slice(0,32);return [{json:{...x,final_trace_id:trace_id,observability:{parent_trace_id:x.parent_trace_id,stage_trace_id:trace_id,ingestion_accepted:true}}}];`);
setCode(final, 'Return Final Validation Result', `const x=$input.first().json;return [{json:{...x,stage:'final_validation',execution_status:'passed',decision:'complete'}}];`);
save('prd-genie-s2-final-validator-export-v0.1.json', final);

const parent = base(load('prd-genie-realistic-six-source-google-drive-io-main-orchestrator-v0.13.json'), 'S2_ Dynamic Realistic Six-Source Main Orchestrator v0.1.2');
setWorkflowRef(parent, 'Execute Google Drive Clarification Gate v0.12.0', ids.gate, 'S2_ Dynamic Drive and Clarification Gate v0.1');
setWorkflowRef(parent, 'Execute Human Approval Tail v0.1', ids.approval, 'S2_ Dynamic Human Approval v0.1');
setWorkflowRef(parent, 'Execute Production PRD v0.1', ids.prd, 'S2_ Dynamic Production PRD Generator v0.1');
setWorkflowRef(parent, 'Execute Story Breakdown v0.2', ids.story, 'S2_ Dynamic Story Breakdown v0.1');
setWorkflowRef(parent, 'Execute Final Validator v0.1', ids.final, 'S2_ Dynamic Final Validator and Export v0.1');
setCode(parent, 'Validate Dynamic Gate Output', `const x=$input.first().json;if(x.execution_status!=='passed'||x.next_route!=='human_approval'||x.unsupported_claims!==0)throw new Error('S2 parent blocked at gate');return [{json:{...x,stage:'clarification_gate'}}];`);
setCode(parent, 'Validate Dynamic Approval Output', `const x=$input.first().json;if(x.stage!=='human_approval'||x.execution_status!=='passed'||x.validation?.orphan_citations!==0)throw new Error('S2 parent blocked at approval');return [{json:x}];`);
setCode(parent, 'Validate Dynamic PRD Output', `const x=$input.first().json;if(x.stage!=='production_prd'||x.execution_status!=='passed'||x.validation?.orphan_items!==0)throw new Error('S2 parent blocked at PRD');return [{json:x}];`);
setCode(parent, 'Validate Dynamic Story Output', `const x=$input.first().json;if(x.stage!=='story_breakdown'||x.execution_status!=='passed'||x.validation?.orphan_delivery_items!==0)throw new Error('S2 parent blocked at story');return [{json:x}];`);
setCode(parent, 'Return Connected Production Result', `const x=$input.first().json;if(x.stage!=='final_validation'||x.execution_status!=='passed'||!x.validation?.bidirectional_traceability)throw new Error('S2 parent blocked at final validation');return [{json:x}];`);
setCode(parent, 'Prepare Validated Drive Exports', `const final=$input.first().json;if(final.execution_status!=='passed'||final.validation?.groundedness_percent!==100||final.validation?.unsupported_claims!==0||Object.entries(final.validation).some(([k,v])=>k.startsWith('orphan_')&&v!==0))throw new Error('S2 Drive export blocked');const safe=final.run_id.replace(/[^A-Za-z0-9._-]/g,'-'),stamp=new Date().toISOString().replace(/[:.]/g,'-'),summary={run_id:final.run_id,starting_point:{input_documents:final.reconciliation.source_documents,citations:final.reconciliation.citations_indexed},ending_point:final.counts,reconciliation:final.reconciliation,groundedness_percent:100,unsupported_claims:0},story_breakdown={schema_version:'2.0.0',artifact_type:'story_breakdown',run_id:final.run_id,packet_id:final.packet_id,parent_trace_id:final.parent_trace_id,source_manifest:final.source_packet.sources.map(s=>({source_id:s.source_id,source_name:s.source_name,source_hash:s.source_hash,drive_file_id:s.provenance?.drive_file_id})),counts:final.counts,validation:final.validation,epics:final.epics},files=[{file_name:safe+'-'+stamp+'-run-summary.json',mime_type:'application/json',content:JSON.stringify(summary,null,2)},{file_name:safe+'-'+stamp+'-final-prd.md',mime_type:'text/markdown',content:final.final_export.content},{file_name:safe+'-'+stamp+'-story-breakdown.json',mime_type:'application/json',content:JSON.stringify(story_breakdown,null,2)},{file_name:safe+'-'+stamp+'-traceability.json',mime_type:'application/json',content:JSON.stringify({source_packet:final.source_packet,citation_dispositions:final.citation_dispositions,item_dispositions:final.item_dispositions,prd_elements:final.prd_elements,epics:final.epics,reconciliation:final.reconciliation},null,2)}];return files.map(f=>({json:{run_id:final.run_id,file_name:f.file_name,mime_type:f.mime_type,output_folder_id:'1DoTRyMj2ucxkD3B8_Oq5fc02TfS0rvVp',run_summary:summary},binary:{data:{data:Buffer.from(f.content,'utf8').toString('base64'),mimeType:f.mime_type,fileName:f.file_name}}}));`);
setCode(parent, 'Confirm Validated Drive Delivery', `const uploaded=$input.all(),final=$('Return Connected Production Result').first().json;if(uploaded.length!==4||uploaded.some(i=>!i.json.id&&!i.json.webViewLink)||!uploaded.some(i=>String(i.json.name||'').endsWith('-story-breakdown.json')))throw new Error('S2 Drive delivery confirmation failed');return [{json:{...final,drive_delivery:{status:'passed',folder_id:'1DoTRyMj2ucxkD3B8_Oq5fc02TfS0rvVp',file_count:uploaded.length,files:uploaded.map(i=>({id:i.json.id,name:i.json.name,webViewLink:i.json.webViewLink}))}}}];`);
save('prd-genie-s2-realistic-six-source-main-orchestrator-v0.1.json', parent);

console.log('Built 8 S2 dynamic workflow exports.');
