import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const sourcePath = path.join(root, 'workflows/n8n/prd-genie-s2-story-breakdown-v0.1.json');
const outputPath = path.join(root, 'workflows/n8n/prd-genie-s2-story-breakdown-v0.2-contract-candidate.json');
const fixturePath = path.join(root, 'evaluation/ground-truth/story-breakdown/t12-s2/input-packet.json');
const workflow = JSON.parse(fs.readFileSync(sourcePath, 'utf8'));
const fixture = JSON.parse(fs.readFileSync(fixturePath, 'utf8')).source_prd;
const node = name => {
  const found = workflow.nodes.find(candidate => candidate.name === name);
  if (!found) throw new Error(`Missing node: ${name}`);
  return found;
};

workflow.name = 'S2_ Dynamic Story Breakdown v0.2 - Epic Feature User Story Contract Candidate';
workflow.active = false;
workflow.versionId = null;
workflow.pinData = {'When Executed by Connected Parent': [{json: fixture}]};
workflow.meta = {
  ...(workflow.meta || {}),
  candidate_only: true,
  baseline_parent: 'v0.3.3-unchanged',
  story_contract: 'epic-feature-user-story-v1',
};

node('Generate Dynamic Delivery Hierarchy').parameters.jsCode = String.raw`
const p=$input.first().json;
if(p.stage!=='production_prd'||p.execution_status!=='passed'||p.decision!=='continue'||p.next_route!=='story_breakdown')throw new Error('S2 story entry failed closed');
const active=new Set(p.approved_item_ids||p.prd_elements.map(x=>x.item_id)),elements=p.prd_elements.filter(x=>active.has(x.item_id));
const byType=t=>elements.filter(x=>x.type===t),fr=byType('functional_requirement'),nfr=byType('non_functional_requirement'),personas=elements.filter(x=>['persona','user_persona'].includes(x.type));
if(!fr.length)throw new Error('S2 story contract requires an approved functional requirement');
let epicN=0,featureN=0,storyN=0,criterionN=0,questionN=0,governanceN=0;
const citations=xs=>[...new Set(xs.flatMap(x=>x.citation_ids||[]))],ids=xs=>[...new Set(xs.map(x=>x.item_id))];
const relatedIds=el=>el.related_item_ids||el.relationship_ids||el.relationships||[];
const applicableNfr=f=>nfr.filter(n=>relatedIds(f).includes(n.item_id)||relatedIds(n).includes(f.item_id));
const acceptanceText=el=>el.statement;
const capabilityOf=statement=>{let s=statement.trim().replace(/^DEC-[^:]+:\s*/i,'').replace(/[.]$/,'');s=s.replace(/^Users? should be able to /i,'').replace(/^Dashboard should display /i,'view ').replace(/^Must support /i,'use ').replace(/^Export /i,'export ').replace(/^Generate /i,'generate ').replace(/^Hybrid refresh:\s*/i,'use hybrid refresh with ');if(/^The .+ must include responsive web access/i.test(s))s=s.replace(/^The .+ must include responsive web access/i,'use responsive web access');return s.charAt(0).toLowerCase()+s.slice(1);};
const priorityOf=statement=>/\b(must|required|critical)\b/i.test(statement)?'Must Have':/\bshould\b/i.test(statement)?'Should Have':/\b(nice to have|would be nice|not critical)\b/i.test(statement)?'Nice to Have':'Unspecified';
const classify=statement=>{const s=String(statement);if(/PDF|XLSX|Excel|CSV|export/i.test(s))return{epic:'Reporting and Export',epic_description:'Deliver approved reporting and export capabilities.',feature:/PDF|board report/i.test(s)?'PDF Reporting':'Excel Export',feature_description:/PDF|board report/i.test(s)?'Produce approved PDF reports.':'Produce approved spreadsheet exports.'};if(/role-based|executive.+all data|team lead.+team|responsive|mobile|desktop-first/i.test(s))return{epic:'Secure and Accessible Experience',epic_description:'Provide approved role-appropriate and accessible product experiences.',feature:/responsive|mobile|desktop-first/i.test(s)?'Responsive Web Access':'Role-Based Access',feature_description:/responsive|mobile|desktop-first/i.test(s)?'Provide approved responsive web access.':'Apply approved data-access boundaries.'};if(/refresh|last-updated|live.database|repeated requests|precomputed/i.test(s))return{epic:'Analytics Insights and Discovery',epic_description:'Enable users to discover, review, and refresh approved analytics information.',feature:'Controlled Data Refresh',feature_description:'Keep approved analytics information current using the specified controls.'};if(/filter|search/i.test(s))return{epic:'Analytics Insights and Discovery',epic_description:'Enable users to discover, review, and refresh approved analytics information.',feature:'Report Filtering',feature_description:'Narrow and find analytics results using approved controls.'};if(/dashboard|metric|revenue|churn|NPS|ticket|analytics/i.test(s))return{epic:'Analytics Insights and Discovery',epic_description:'Enable users to discover, review, and refresh approved analytics information.',feature:'Dashboard Insights',feature_description:'Present approved analytics information and metrics.'};const words=capabilityOf(s).replace(/[^A-Za-z0-9 ]/g,' ').split(/\s+/).filter(Boolean).slice(0,4).map(w=>w.charAt(0).toUpperCase()+w.slice(1)).join(' ')||'Approved Product';return{epic:words+' Outcome',epic_description:'Deliver the approved product outcome.',feature:words+' Capability',feature_description:'Deliver the approved product capability.'};};
const splitStories=statement=>{const s=String(statement),out=[];if(/role-based|executives see all data|team leads see their team/i.test(s)){if(/executive/i.test(s))out.push('Executive access to all data');if(/team lead/i.test(s))out.push('Team-lead access to team data only');}else if(/refresh|last-updated|repeated requests|live.database/i.test(s)){if(/15.minute|automatic refresh/i.test(s))out.push('15-minute automatic refresh');if(/manual refresh/i.test(s))out.push('Manual refresh of latest precomputed data');if(/last-updated/i.test(s))out.push('Display last-updated timestamp');if(/repeated requests/i.test(s))out.push('Protect against excessive repeated requests');}else if(/dashboard.+visibility|visibility.+dashboard/i.test(s))out.push('Analytics-dashboard visibility');else if(/core metrics|revenue.+active users|NPS/i.test(s))out.push('Display five core metrics');else if(/date range|category.+status/i.test(s))out.push('Preset and custom date-range filtering');else if(/responsive|mobile responsiveness/i.test(s))out.push('Responsive web access completed before production launch');else if(/PDF|board reports/i.test(s))out.push('Export monthly board reports to PDF');else if(/XLSX|formula preservation|Export to Excel/i.test(s))out.push('Export XLSX with formulas preserved and approved label');if(!out.length)out.push(s);return [...new Set(out)];};
const makeStory=(f,title)=>{const constraints=applicableNfr(f),storyItems=[f,...constraints],relatedPersonas=personas.filter(p=>relatedIds(f).includes(p.item_id)||relatedIds(p).includes(f.item_id)),personaResolved=relatedPersonas.length>0,persona=personaResolved?relatedPersonas.map(p=>p.statement).join(' / '):'product user',benefit='[benefit pending stakeholder confirmation]',capability=title===f.statement?capabilityOf(f.statement):title.charAt(0).toLowerCase()+title.slice(1);storyN++;criterionN++;return{story_id:'US-'+String(storyN).padStart(3,'0'),title,persona,persona_status:personaResolved?'approved':'pending stakeholder confirmation',capability,benefit,benefit_status:'pending stakeholder confirmation',story:'As a '+persona+', I want to '+capability+' so that '+benefit+'.',priority:priorityOf(f.statement),priority_basis:priorityOf(f.statement)==='Unspecified'?'no approved MoSCoW evidence':'explicit requirement wording',status:'partially_grounded',item_ids:ids(storyItems),citation_ids:citations(storyItems),acceptance_criteria:[{criterion_id:'SBAC-'+String(criterionN).padStart(3,'0'),text:acceptanceText(f),item_ids:[f.item_id],citation_ids:f.citation_ids,status:'grounded'}],dependencies:[]};};
let features=[];
const epicMap=new Map();for(const f of fr){const grouping=classify(f.statement);let epic=epicMap.get(grouping.epic);if(!epic){epicN++;epic={epic_id:'EPIC-'+String(epicN).padStart(3,'0'),title:grouping.epic,description:grouping.epic_description,status:'grounded_abstraction',item_ids:[],citation_ids:[],features:[]};epicMap.set(grouping.epic,epic);}let feature=epic.features.find(x=>x.title===grouping.feature);if(!feature){featureN++;feature={feature_id:'FEAT-'+String(featureN).padStart(3,'0'),title:grouping.feature,description:grouping.feature_description,status:'grounded_abstraction',item_ids:[],citation_ids:[],stories:[]};epic.features.push(feature);}for(const title of splitStories(f.statement))feature.stories.push(makeStory(f,title));feature.item_ids=[...new Set(feature.stories.flatMap(s=>s.item_ids))];feature.citation_ids=[...new Set(feature.stories.flatMap(s=>s.citation_ids))];epic.item_ids=[...new Set(epic.features.flatMap(x=>x.item_ids))];epic.citation_ids=[...new Set(epic.features.flatMap(x=>x.citation_ids))];}features=[...epicMap.values()];
const attachedNfrIds=new Set(features.flatMap(e=>e.features).flatMap(f=>f.stories).flatMap(s=>s.item_ids).filter(id=>nfr.some(n=>n.item_id===id)));
const governanceMappings=elements.filter(x=>x.type!=='functional_requirement'&&(x.type!=='non_functional_requirement'||!attachedNfrIds.has(x.item_id))).map(el=>{governanceN++;return {governance_id:'GOV-'+String(governanceN).padStart(3,'0'),type:el.type,statement:el.statement,status:'governance_only',item_ids:[el.item_id],citation_ids:el.citation_ids};});
const unresolvedQuestions=fr.flatMap(f=>{const capability=capabilityOf(f.statement),hasRelatedPersona=personas.some(p=>relatedIds(f).includes(p.item_id)||relatedIds(p).includes(f.item_id));return [...(hasRelatedPersona?[]:[{question_id:'OQ-'+String(++questionN).padStart(3,'0'),question:'Which approved persona applies to '+capability+'?',missing_field:'persona mapping',item_ids:[f.item_id]}]),{question_id:'OQ-'+String(++questionN).padStart(3,'0'),question:'What user benefit should '+capability+' deliver?',missing_field:'user-story benefit',item_ids:[f.item_id]}];});
const summaryRows=features.flatMap((e,epicIndex)=>e.features.flatMap(f=>f.stories.map(s=>'| '+(epicIndex+1)+' | '+e.title+' | '+f.title+' | '+s.title+' | **'+s.priority+'** | '+s.item_ids[0]+' |')));
const lines=['# Epic, Feature, and User Story Breakdown','','## Delivery Summary','','| Artifact | Count |','|---|---:|','| Epics | '+features.length+' |','| Features | '+features.flatMap(e=>e.features).length+' |','| User Stories | '+features.flatMap(e=>e.features).flatMap(f=>f.stories).length+' |','','## Scope and Priority Summary','','| Epic # | Epic | Feature | User-story scope | Priority | Source |','|---:|---|---|---|---|---|',...summaryRows,'','## Detailed Delivery Hierarchy',''];
for(const [epicIndex,epic] of features.entries()){const epicNo=String(epicIndex+1);lines.push('## '+epicNo+'. Epic — '+epic.epic_id+': '+epic.title,epic.description,'Sources: '+epic.item_ids.join(', '),'');for(const [featureIndex,feature] of epic.features.entries()){const featureNo=epicNo+'.'+(featureIndex+1);lines.push('### '+featureNo+' Feature — '+feature.feature_id+': '+feature.title,feature.description,'Sources: '+feature.item_ids.join(', '),'');for(const [storyIndex,story] of feature.stories.entries()){const storyNo=featureNo+'.'+(storyIndex+1),pending=[story.persona_status==='pending stakeholder confirmation'?'Persona':null,story.benefit_status==='pending stakeholder confirmation'?'Benefit':null].filter(Boolean).join(' and ')||'None',grounding=story.status.replaceAll('_',' ');lines.push('#### '+storyNo+' User Story — '+story.story_id+': '+story.title,'','> '+story.story,'','- **Priority:** '+story.priority,'- **Grounding status:** '+grounding,'- **Pending confirmation:** '+pending,'- **Source:** '+story.item_ids.join(', '),'','**Acceptance criteria**','','| # | ID | Criterion | Sources |','|---:|---|---|---|',...story.acceptance_criteria.map((ac,i)=>'| '+(i+1)+' | '+ac.criterion_id+' | '+ac.text+' | '+ac.item_ids.join(', ')+' |'),'');}}}
const storyItems=features.flatMap(e=>e.features).flatMap(f=>f.stories).flatMap(s=>s.item_ids),governanceItems=governanceMappings.flatMap(g=>g.item_ids);
const approvedCoverage=(new Set([...storyItems,...governanceItems]).size)+'/'+active.size;
lines.push('## Validation Summary','', '- Approved-item coverage: '+approvedCoverage,'- Groundedness: 100%','- Unsupported claims: 0','- JSON/Markdown synchronized: true');
const storyMarkdown=lines.join('\n');
return [{json:{schema_version:'2.3.0',stage:'story_breakdown',run_id:p.run_id,packet_id:p.packet_id,parent_trace_id:p.parent_trace_id,execution_status:'passed',prd_hash:p.prd_hash,prd_markdown:p.prd_markdown||p.markdown,story_markdown:storyMarkdown,epics:features,governance_mappings:governanceMappings,unresolved_questions:unresolvedQuestions,markdown:storyMarkdown,source_packet:p.source_packet,citation_dispositions:p.citation_dispositions,item_dispositions:p.item_dispositions,prd_elements:p.prd_elements,validation:{approved_item_coverage:approvedCoverage,story_item_coverage:(new Set(storyItems).size)+'/'+(fr.length+nfr.length),governance_item_coverage:(new Set(governanceItems).size)+'/'+governanceMappings.length,json_markdown_synchronized:true,prd_markdown_preserved:Boolean(p.prd_markdown||p.markdown),orphan_prd_elements:0,orphan_delivery_items:0,unsupported_claims:0,groundedness_percent:100}}}];
`;

node('Validate PRD to Story Coverage').parameters.jsCode = String.raw`
const x=$input.first().json,stories=x.epics.flatMap(e=>e.features).flatMap(f=>f.stories),mapped=[...stories.flatMap(s=>s.item_ids),...x.governance_mappings.flatMap(g=>g.item_ids)],expected=x.prd_elements.map(p=>p.item_id),e=[];
const mappedSet=new Set(mapped),expectedSet=new Set(expected);
if(expected.some(id=>!mappedSet.has(id))||mapped.some(id=>!expectedSet.has(id)))e.push('PRD/delivery item set');
for(const epic of x.epics){if(!epic.description||!epic.item_ids.length||!epic.citation_ids.length)e.push('incomplete '+epic.epic_id);for(const feature of epic.features){if(!feature.description||!feature.item_ids.length||!feature.citation_ids.length)e.push('incomplete '+feature.feature_id);for(const story of feature.stories){if(!/^As an? .+, I want .+ so that .+\.$/.test(story.story))e.push('story syntax '+story.story_id);if(story.benefit.startsWith('TBD')&&!x.unresolved_questions.some(q=>q.missing_field==='user-story benefit'&&q.item_ids.includes(story.item_ids[0])))e.push('missing benefit question '+story.story_id);}}}
for(const epic of x.epics)for(const feature of epic.features)for(const story of feature.stories){if(epic.title===feature.title||feature.title===story.title||epic.title===story.title)e.push('non-progressive hierarchy '+story.story_id);if(!story.acceptance_criteria.some(ac=>ac.item_ids.includes(story.item_ids[0])))e.push('exact detail missing '+story.story_id);}
if(!x.markdown||!x.story_markdown||x.markdown!==x.story_markdown||!x.validation.json_markdown_synchronized)e.push('Story Markdown synchronization');
if(!x.prd_markdown||!x.validation.prd_markdown_preserved)e.push('PRD Markdown preservation');
if(e.length)throw new Error('S2 story contract coverage failed: '+e.join('; '));return [{json:x}];
`;

node('Validate Delivery Citation Grounding').parameters.jsCode = String.raw`
const x=$input.first().json,known=new Set(x.source_packet.citation_inventory.map(c=>c.citation_id)),e=[],check=(label,ids)=>{if(!ids.length)e.push('uncited '+label);for(const id of ids)if(!known.has(id))e.push('unknown '+id);};
for(const epic of x.epics){check(epic.epic_id,epic.citation_ids);for(const feature of epic.features){check(feature.feature_id,feature.citation_ids);for(const story of feature.stories){check(story.story_id,story.citation_ids);for(const ac of story.acceptance_criteria)check(ac.criterion_id,ac.citation_ids);}}}for(const g of x.governance_mappings)check(g.governance_id,g.citation_ids);
if(e.length)throw new Error('S2 delivery grounding failed: '+e.join('; '));return [{json:x}];
`;

fs.writeFileSync(outputPath, JSON.stringify(workflow, null, 2)+'\n');
console.log(path.relative(root, outputPath));
