import crypto from 'node:crypto';
import fs from 'node:fs';
const input='workflows/n8n/prd-genie-requirement-extractor-child-v1.7.json';
const output='workflows/n8n/prd-genie-requirement-extractor-child-v1.8.json';
const packet=JSON.parse(fs.readFileSync('evaluation/fixtures/multi-source/realistic-v1/source-packet-v3.json','utf8'));
const amendment=JSON.parse(fs.readFileSync('evaluation/fixtures/multi-source/realistic-v1/stakeholder-clarification-amendment-2026-08-07.json','utf8'));
const workflow=JSON.parse(fs.readFileSync(input,'utf8'));workflow.name='PRD Genie - Requirement Extractor Child v1.8';workflow.versionId=crypto.randomUUID();
const trace=workflow.nodes.find(n=>n.name==='Create Trace Context');trace.parameters.jsCode=trace.parameters.jsCode.replace('child-v1.7.0','child-v1.8.0').replace('extractor-v1.12-deterministic-coverage-ledger','extractor-v1.13-authoritative-amendment-precedence');
const validate=workflow.nodes.find(n=>n.name==='Validate and Adapt Source Input');
validate.parameters.jsCode=validate.parameters.jsCode
 .replace(`if (data.packet_id === 'SP-REALISTIC-PB-MT-SN-CLAR-V2') {`,`if (data.packet_id === '${packet.packet_id}') {\n  if (data.run_id !== '${packet.run_id}') errors.push('v3 run_id mismatch');\n  if (data.sources.length !== 5) errors.push('v3 packet requires exactly five sources');\n} else if (data.packet_id === 'SP-REALISTIC-PB-MT-SN-CLAR-V2') {`)
 .replace(`const expectedTypes = data.packet_id === 'SP-REALISTIC-PB-MT-SN-CLAR-V2' ? ['meeting_transcript','product_brief','stakeholder_clarification','stakeholder_notes'] : ['meeting_transcript','product_brief','stakeholder_notes'];`,`const expectedTypes = ['${packet.packet_id}','SP-REALISTIC-PB-MT-SN-CLAR-V2'].includes(data.packet_id) ? ['meeting_transcript','product_brief','stakeholder_clarification','stakeholder_notes'] : ['meeting_transcript','product_brief','stakeholder_notes'];`)
 .replace(`if (data.packet_id === 'SP-REALISTIC-PB-MT-SN-CLAR-V2') {\n  const expectedHashes=`,`if (data.packet_id === '${packet.packet_id}') {\n  const expectedHashes=${JSON.stringify(Object.fromEntries(packet.sources.map(s=>[s.source_id,s.content_hash])))};\n  for (const source of data.sources) if (expectedHashes[source.source_id] !== source.content_hash) errors.push('unapproved v3 source/hash '+source.source_id);\n  const amendmentSource=data.sources.find(s=>s.source_id==='SRC-REALISTIC-CLAR-AMEND-001');\n  const expectedAmendments=${JSON.stringify(amendment.amendments.map(a=>({id:a.decision_id,location:a.clarification_source_citation.location,quote:a.clarification_source_citation.quote})))};\n  if (!amendmentSource) errors.push('authoritative amendment source missing');\n  else for (const decision of expectedAmendments) { const citation=(amendmentSource.citations||[]).find(c=>c.location===decision.location&&c.quote===decision.quote); if(!citation||!citation.quote.includes(decision.id))errors.push('amendment citation mismatch '+decision.id); }\n+} else if (data.packet_id === 'SP-REALISTIC-PB-MT-SN-CLAR-V2') {\n  const expectedHashes=`);
const extractor=workflow.nodes.find(n=>n.name==='Requirement Extractor');
const rule=`\n\nv1.13 authoritative amendment precedence: For packet ${packet.packet_id}, SRC-REALISTIC-CLAR-AMEND-001 is later authoritative evidence. DEC-2026-08-07-GAP-008-A1 makes budget approval non-blocking for PRD completion, assigns Sarah, and changes the deadline to September 10, 2026 while retaining existing cost constraints. DEC-2026-08-07-GAP-014-A1 selects SPA and supersedes the deferred technical evaluation. Preserve prior decisions as history but apply the amendments as current state. Do not emit missing information or contradictions for the superseded budget prerequisite, August 31 deadline, or SPA-versus-server-rendered choice.`;
extractor.parameters.text+=rule;extractor.parameters.messages.messageValues[0].message+=rule;
validate.parameters.jsCode=validate.parameters.jsCode.replace('\n+} else if','\n} else if');
fs.writeFileSync(output,JSON.stringify(workflow,null,2)+'\n');console.log(`Wrote ${output}`);
