import crypto from 'node:crypto';
import fs from 'node:fs';

const extractorId = process.argv[2];
const gapId = process.argv[3] || 'wGBE80XMjD5rTKql';
if (!extractorId) throw new Error('Extractor workflow ID is required');
const packet = JSON.parse(fs.readFileSync('evaluation/fixtures/multi-source/realistic-v1/source-packet-v2.json','utf8'));
const decisions = JSON.parse(fs.readFileSync('evaluation/fixtures/multi-source/realistic-v1/stakeholder-clarification-decisions-2026-08-07.json','utf8'));
const id=()=>crypto.randomUUID();
const nodes=[
 {parameters:{},id:id(),name:'Manual Trigger',type:'n8n-nodes-base.manualTrigger',typeVersion:1,position:[-800,0]},
 {parameters:{jsCode:`const packet=${JSON.stringify(packet)}; const decisions=${JSON.stringify(decisions)}; const parent_trace_id=Array.from({length:32},()=>Math.floor(Math.random()*16).toString(16)).join(''); return [{json:{...packet,submitted_at:new Date().toISOString(),orchestration_context:{parent_trace_id,active_run_id:packet.run_id,test_id:'REALISTIC-CLARIFICATION-V2',environment:'realistic-clarification-canary'},clarification_contract:{decision_maker:decisions.decision_maker,decision_date:decisions.decision_date,decision_ids:decisions.decisions.map(d=>d.decision_id),supersessions:decisions.decisions.filter(d=>d.supersedes.length).map(d=>({decision_id:d.decision_id,supersedes:d.supersedes}))}}}];`},id:id(),name:'Load Approved Four-Source Packet v2',type:'n8n-nodes-base.code',typeVersion:2,position:[-560,0]},
 {parameters:{source:'database',workflowId:{__rl:true,value:extractorId,mode:'list',cachedResultName:'PRD Genie - Requirement Extractor Child v1.6'},mode:'once',options:{waitForSubWorkflow:true}},id:id(),name:'Execute Requirement Extractor Child v1.6',type:'n8n-nodes-base.executeWorkflow',typeVersion:1.3,position:[-280,0]},
 {parameters:{jsCode:`const stage=$input.first().json; const original=$('Load Approved Four-Source Packet v2').first().json; const errors=[]; if(stage.stage!=='requirement_extraction'||stage.execution_status!=='passed')errors.push('extractor stage'); if(stage.run_id!==original.run_id)errors.push('run_id'); if(stage.groundedness_percent!==100||stage.validation?.unsupported_claims!==0)errors.push('grounding'); if(!stage.observability?.ingestion_accepted)errors.push('extractor Langfuse'); if(stage.observability?.parent_trace_id!==original.orchestration_context.parent_trace_id)errors.push('extractor parent trace'); if(stage.validation?.source_route!=='production_multi_source')errors.push('source route'); if(stage.source_packet?.packet_id!==original.packet_id)errors.push('packet ID'); if((stage.source_packet?.sources||[]).length!==4)errors.push('source count'); if('source_text' in original||'input_type' in original)errors.push('mixed eval producer'); const expected=new Map(original.sources.map(s=>[s.source_id,s.content_hash])); for(const s of stage.source_packet?.sources||[])if(expected.get(s.source_id)!==s.content_hash)errors.push('source/hash '+s.source_id); const notes=stage.output?.extractor_notes||[]; if(notes.length!==original.sources.reduce((n,s)=>n+s.citations.length,0))errors.push('citation ledger coverage'); if(errors.length)throw new Error('Four-source extraction acceptance failed: '+[...new Set(errors)].join('; ')); return [{json:{schema_version:'1.0.0',run_id:stage.run_id,extraction:stage.output,orchestration_context:original.orchestration_context,requirement_extraction_stage:stage,clarification_contract:original.clarification_contract}}];`},id:id(),name:'Validate Four-Source Extraction',type:'n8n-nodes-base.code',typeVersion:2,position:[0,0]},
 {parameters:{source:'database',workflowId:{__rl:true,value:gapId,mode:'list',cachedResultName:'PRD Genie - Gap Analyzer Child v1.0'},mode:'once',options:{waitForSubWorkflow:true}},id:id(),name:'Execute Gap Analyzer Child v1.0',type:'n8n-nodes-base.executeWorkflow',typeVersion:1.3,position:[280,0]},
 {parameters:{jsCode:`const gap=$input.first().json; const prior=$('Validate Four-Source Extraction').first().json; const errors=[]; if(gap.stage!=='gap_analysis'||gap.execution_status!=='passed')errors.push('gap stage'); if(gap.run_id!==prior.run_id)errors.push('run_id'); if(gap.groundedness_percent!==100)errors.push('gap grounding'); if(!gap.observability?.ingestion_accepted)errors.push('gap Langfuse'); if(gap.observability?.parent_trace_id!==prior.orchestration_context.parent_trace_id)errors.push('gap parent trace'); const gate=gap.output?.generation_gate; if(!gate)errors.push('generation gate'); if(errors.length)throw new Error('Four-source gap acceptance failed: '+errors.join('; ')); return [{json:{schema_version:'1.0.0',result_type:'realistic_clarification_v2_canary',run_id:prior.run_id,execution_status:'completed',contract_status:'passed',packet_id:'SP-REALISTIC-PB-MT-SN-CLAR-V2',source_count:4,decision_count:prior.clarification_contract.decision_ids.length,decision_ids:prior.clarification_contract.decision_ids,supersessions:prior.clarification_contract.supersessions,parent_trace_id:prior.orchestration_context.parent_trace_id,requirement_extraction_trace_id:prior.requirement_extraction_stage.observability.stage_trace_id,gap_analysis_trace_id:gap.observability.stage_trace_id,requirement_extraction:prior.requirement_extraction_stage,gap_analysis:gap,groundedness_percent:100,unsupported_claims:0,next_route:gap.next_route,stopped_before_human_approval:gap.next_route==='human_approval',recorded_at:new Date().toISOString()}}];`},id:id(),name:'Validate Clarification Runtime and Stop',type:'n8n-nodes-base.code',typeVersion:2,position:[560,0]}
];
const names=nodes.map(n=>n.name); const connections={}; for(let i=0;i<names.length-1;i++)connections[names[i]]={main:[[{node:names[i+1],type:'main',index:0}]]};
const workflow={name:'PRD Genie - Realistic Clarification v2 Canary v0.1',nodes,pinData:{},connections,active:false,settings:{executionOrder:'v1'},versionId:id(),meta:{templateCredsSetupCompleted:true},tags:[]};
fs.writeFileSync('workflows/n8n/prd-genie-realistic-clarification-v2-canary-v0.1.json',JSON.stringify(workflow,null,2)+'\n');
console.log('Wrote clarification canary');
