import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const root=path.resolve(import.meta.dirname,'..');
const workflow=JSON.parse(fs.readFileSync(path.join(root,'workflows/n8n/prd-genie-s2-final-validator-export-v0.3-full-markdown-candidate.json'),'utf8'));
const code=name=>workflow.nodes.find(n=>n.name===name).parameters.jsCode;
const base={source_packet:{source_manifest:[{}],citation_inventory:[{citation_id:'C1'},{citation_id:'C2'}]},citation_dispositions:[{citation_id:'C1'},{citation_id:'C2'}],prd_elements:[{item_id:'FR-1',statement:'Users can filter reports.',citation_ids:['C1']},{item_id:'PER-1',statement:'Reporting analyst.',citation_ids:['C2']}],epics:[{features:[{stories:[{item_ids:['FR-1'],citation_ids:['C1']}]}]}],governance_mappings:[{item_ids:['PER-1'],citation_ids:['C2']} ]};
const run=async (name,input)=>(await new vm.Script(`(async()=>{${code(name)}})()`).runInNewContext({$input:{first:()=>({json:input})}}))[0].json;
const valid=await run('Validate Bidirectional Traceability',base);
if(valid.reconciliation.prd_elements!==2||valid.reconciliation.governance_mappings!==1)throw new Error('Valid story plus governance set failed');
let missing=false;try{await run('Validate Bidirectional Traceability',{...base,governance_mappings:[]});}catch(e){missing=String(e).includes('PRD delivery set');}if(!missing)throw new Error('Missing governance item did not fail closed');
let unknown=false;try{await run('Validate Bidirectional Traceability',{...base,governance_mappings:[{item_ids:['UNKNOWN'],citation_ids:['C2']}]});}catch(e){unknown=String(e).includes('PRD delivery set');}if(!unknown)throw new Error('Unknown governance item did not fail closed');
const headings=['## 1. Product Overview','## 2. Goals and Objectives','## 3. User Personas','## 4. Feature Requirements','## 5. Acceptance Criteria','## 6. Out of Scope','## 7. Dependencies and Risks','## 8. Assumptions','## 9. Open Questions','## 10. Timeline'];
const prdMarkdown='# Product Requirements Document\n\n'+headings.join('\n\nContent\n\n');
const storyMarkdown='# Story Breakdown\n\n## 1. Epic — EPIC-001: Filtering';
const exported=await run('Build Dynamic Final Export',{...valid,run_id:'RUN-TEST',packet_id:'PKT-TEST',parent_trace_id:'TRACE-TEST',prd_markdown:prdMarkdown,story_markdown:storyMarkdown,epics:[{features:[{stories:[{item_ids:['FR-1'],citation_ids:['C1'],acceptance_criteria:[]}]}]}]});
if(exported.final_export.content!==prdMarkdown)throw new Error('Full PRD Markdown was changed during export');
if(exported.story_export.content!==storyMarkdown)throw new Error('Story Markdown was changed during export');
if(!exported.prd_review_export.content.includes('Validated full-chain PRD review'))throw new Error('PRD review Markdown was not generated');
if(!exported.prd_review_export.content.endsWith(prdMarkdown))throw new Error('PRD review does not preserve the validated PRD');
if(!exported.story_review_export.content.startsWith('# PRD Genie S2 - Validated Epic Feature User Story Review - RUN-TEST'))throw new Error('Story review heading is not run-specific');
if(!exported.story_review_export.content.endsWith(storyMarkdown))throw new Error('Story review does not preserve the validated hierarchy');
if(exported.prd_review_export.file_name!=='PRD Genie S2 - Validated Full PRD Review - RUN-TEST.md')throw new Error('PRD review filename is not run-specific');
if(exported.story_review_export.file_name!=='PRD Genie S2 - Validated Epic Feature User Story Review - RUN-TEST.md')throw new Error('Story review filename is not run-specific');
if(!exported.traceability_export.content.startsWith('# PRD Genie S2 Traceability Summary'))throw new Error('Traceability summary was not explicitly distinguished');
if(exported.validation.required_prd_sections!==10)throw new Error('Ten-section PRD contract was not validated');
let incomplete=false;try{await run('Build Dynamic Final Export',{...valid,prd_markdown:prdMarkdown.replace(headings[9],''),story_markdown:storyMarkdown,epics:[]});}catch(e){incomplete=String(e).includes('missing PRD section');}if(!incomplete)throw new Error('Incomplete PRD did not fail closed');
console.log('PASS: traceability closes; full PRD and story Markdown are preserved exactly; incomplete PRD fails closed');
